#!/bin/sh

#
# Automatically include the branch story ID in the commit message.
#

STORY_ID=$(git rev-parse --abbrev-ref HEAD | grep -Eo "^[0-9]{5,}")

if [ -n "$STORY_ID" ] ;then
  echo "" >> "$1"
  echo "[#$STORY_ID]" >> "$1"
fi
